# Generated by Django 5.2.4 on 2025-08-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='applied',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='new_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
